spring:
  application:
    name: limit_process
  datasource:
    url: jdbc:postgresql://localhost:5432/limit_process_db
    username: limit_process_user
    password: limit_process_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  queue: application-limit-process

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

server:
  port: 8085
