databaseChangeLog:
  - changeSet:
      id: 1
      author: user
      changes:
        - createTable:
            tableName: product
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: case_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: type
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: owner
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: margin
                  type: DECIMAL(10,2)
