spring:
  application:
    name: checklist
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

rabbitmq:
  queue: application-checklist

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

server:
  port: 8081
